Animal_Shelter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from shelter_app.views import RegistrationView, NewAnimalView, UpdateAnimalView, \
     AdmissionView, OutcomeView, HealthCareView, AnimalsView, AnimalDetail
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='main_page.html'), name='main'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('animals/', AnimalsView.as_view(), name='animals'),
    path('animals/new_animal/', NewAnimalView.as_view(), name='new_animal'),
    path('animals/<pk>/', AnimalDetail.as_view(), name='animal'),
    path('animals/<int:animal_id>/update/', UpdateAnimalView.as_view(), name='update_animal'),
    path('animals/<int:animal_id>/admission/', AdmissionView.as_view(), name='admission'),
    path('animals/<int:animal_id>/outcome/', OutcomeView.as_view(), name='outcome'),
    path('animals/<int:animal_id>/healthcare/', HealthCareView.as_view(), name='health'),
]

shelter_app/models.py
from django.db import models


ADMISSION_SUBJECT = (
    ('G', 'Gminna'),
    ('O', 'Osoba fizyczna'),
    ('SM', 'Straż Miejska'),
    ('P', 'Policja'),
    ('I', 'Inne'),
)

OUTCOME_SUBJECT = (
    ('O', 'Osoba fizyczna'),
    ('F', 'Fundacja'),
    ('S', 'Schronisko'),
    ('I', 'Inne'),
)


OUT_TYPE = (
    ('Z', 'Zaginiony'),
    ('A', 'Adoptowany'),
    ('W', 'Odebrany przez właściciela'),
    ('E', 'Eutanazja'),
    ('ZG', 'Zgon'),
)

VET_TYPE = (
    ('S', 'Szczepienie'),
    ('ZP', 'Zwalczanie pasożytów'),
    ('ZCH', 'Zabieg chirurgiczny'),
    ('SK', 'Sterylizacja/Kastracja'),
    ('I', 'Inne'),
)


class Animal(models.Model):
    name = models.CharField(max_length=64, null=False)
    date_of_birth = models.DateField()
    breed = models.CharField(max_length=64)
    gender = models.CharField(max_length=64)
    color = models.CharField(max_length=64)
    chip_number = models.CharField(max_length=15, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Admission(models.Model):
    admission_date = models.DateField()
    a_name = models.CharField(max_length=64)
    a_address = models.CharField(max_length=128)
    a_subject = models.CharField(max_length=3, choices=ADMISSION_SUBJECT)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, null=True)


class Outcome(models.Model):
    type = models.CharField(max_length=32, choices=OUT_TYPE, null=False)
    outcome_date = models.DateField()
    o_name = models.CharField(max_length=64)
    o_address = models.CharField(max_length=128)
    subject_type = models.CharField(max_length=3, choices=OUTCOME_SUBJECT)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, null=True)


class VeterinaryTreatment(models.Model):
    treat_name = models.CharField(max_length=64)
    vet_type = models.CharField(max_length=3, choices=VET_TYPE)
    animal = models.ManyToManyField(Animal, through='Treatment')


class Treatment(models.Model):
    treat_date = models.DateField(null=False)
    date_of_expire = models.DateField(null=True)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, null=True)
    veterinary_treatment = models.ForeignKey(VeterinaryTreatment, on_delete=models.CASCADE, null=True)

shelter_app/forms.py
from django import forms
from django.contrib.auth.models import User

from shelter_app.models import Animal


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "wprowadzono różne hasła"
            )


class AnimalForm(forms.ModelForm):
    chip_number = forms.IntegerField(required=False)

    class Meta:
        model = Animal
        fields = ['name', 'date_of_birth', 'breed', 'gender', 'color', 'chip_number']
        labels = {
            'name': ('Imię zwierzęcia:'),
            'date_of_birth': ('Rok urodzenia:'),
            'breed': ('Rasa:'),
            'gender': ('Płeć:'),
            'color': ('Umaszczenie:'),
            'chip_number': ('Numer chip:'),
        }

        help_texts = {
            'chip_number': ('Chip musi zawierać 15 znaków.'),
        }


class AdmissionForm(forms.Form):
    admission_date = forms.DateField(label='Data przyjęcia:',  widget=forms.SelectDateWidget)
    a_name = forms.CharField(label="Nazwa oddającego zwierzę:", max_length=64)
    a_address = forms.CharField(label="Adres oddającego:", max_length=128,
                                    widget=forms.TextInput(attrs={'size': '128'}))
    ADMISSION_SUBJECT = (
        ('G', 'Gminna'),
        ('O', 'Osoba fizyczna'),
        ('SM', 'Straż Miejska'),
        ('P', 'Policja'),
        ('I', 'Inne'),
    )
    a_subject = forms.ChoiceField(label="Rodzaj podmiotu:", choices=ADMISSION_SUBJECT, widget=forms.RadioSelect)


class OutcomeForm(forms.Form):
    OUT_TYPE = (
        ('Z', 'Zaginiony'),
        ('A', 'Adoptowany'),
        ('W', 'Odebrany przez właściciela'),
        ('E', 'Eutanazja'),
        ('ZG', 'Zgon'),
    )
    type = forms.ChoiceField(label='Powód wydania:', choices=OUT_TYPE)
    outcome_date = forms.DateField(label='Data wydania:', widget=forms.SelectDateWidget)
    o_name = forms.CharField(label='Podmiot odbierający:', required=False)
    o_address = forms.CharField(label='Adres odbierającego:', max_length=128, required=False,
                                widget=forms.TextInput(attrs={'size': '128'}))
    OUTCOME_SUBJECT = (
        ('O', 'Osoba fizyczna'),
        ('F', 'Fundacja'),
        ('S', 'Schronisko'),
        ('I', 'Inne'),
    )
    subject_type = forms.ChoiceField(label='Typ odbierającego:', required=False, choices=OUTCOME_SUBJECT)
    is_active = forms.BooleanField(required=False)


class HealthCareForm(forms.Form):
    treat_name = forms.CharField(label="Nazwa zabiegu:")
    VET_TYPE = (
        ('S', 'Szczepienie'),
        ('ZP', 'Zwalczanie pasożytów'),
        ('ZCH', 'Zabieg chirurgiczny'),
        ('SK', 'Sterylizacja/Kastracja'),
        ('I', 'Inne'),
    )
    vet_type = forms.ChoiceField(label="Rodzaj zabiegu:", choices=VET_TYPE)
    treat_date = forms.DateField(label="Data zabiegu:", widget=forms.SelectDateWidget)

    OUT_TYPE = (
        ('Z', 'Zaginiony'),
        ('A', 'Adoptowany'),
        ('W', 'Odebrany przez właściciela'),
        ('E', 'Eutanazja'),
        ('ZG', 'Zgon'),
    )
    date_of_expire = forms.DateField(label="Ważność wygasa:", required=False)

templates/admission_form.html
{%  extends 'base.html' %}

{% block content %}
    <h2>Dane dotyczące rejestracji zwierzęcia</h2>

  <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
{% endblock %}

templates/animal.html
{%  extends 'base.html' %}
{%  load static %}
{% block content %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <head>
            <div class="border-top pt-3" style="text-align:right;">
                    <a href="{% url 'animals' %}">Powrót</a>
                    <a href="{% url 'logout' %}">Wyloguj</a>
             </div>

        </head>
    <body>
    <P> Dodaj dane dotyczące:</P>
        <p><a href={% url 'admission' animal.id %}>Przyjęcia </a>
        <a href={% url 'health' animal.id %}>Stanu zdrowia</a>
        <a href={% url 'outcome' animal.id %}>Wydania</a>

   <P> Edytuj dane:</P>
        <a href={% url 'update_animal' animal.id %}>{{ animal.name }}</a>

    <P> </P>



    <div id="strona">
        <div id="naglowek"><h1>Nasz podopieczny - {{ animal.name }}</h1></div>
             </div>
     </div>
        <div class="content">
            <div class="border-top pt-3" style="text-align:left;">
             </div>
         </div>
             <div>
            <table>
                <tr><td> Rasa: </td><td>{{ animal.breed }}</td></tr>
                <tr><td> Data urodzenia: </td><td>{{ animal.date_of_birth |date:"d.m.Y"}} r.</td></tr>
                <tr><td> Kolor umaszczenia: </td><td>{{ animal.color }}</td></tr>
                <tr><td> Płeć: </td><td>{{ animal.gender }}</td></tr>
                {% if animal.is_active == True %}
                    <tr><td> Dostępny do adopcji: </td><td> Tak </td></tr>
                {% else %}
                    <tr><td> Dostępny do adopcji: </td><td> Nie </td></tr>
                {% endif %}
                <tr><td> W schronisku od:</td><td>
                    {% for admission in object.admission_set.all %}
                        {{ admission.admission_date |date:"d.m.Y" }} r.
                    </td></tr>
                    {% endfor %}
            </table>

            </div>


        <strong><P>Dane dotyczące przyjęcia :</P></strong>
 {% for admission in object.admission_set.all %}
<tr><td> Przyjęty: </td><td>{{ admission.admission_date }} r. </td></tr>
     <tr><td> Oddający: </td><td>{{ admission.a_name}}</td></tr>
     <tr><td> Adres: </td><td>{{ admission.a_address }}</td></tr>
  {% endfor %}

          <strong><P>Karta zdrowia:</P></strong>
    <p><td> Przeprowadzone zabiegi: </td></p>
     {% for veterinarytreatment in object.veterinarytreatment_set.all %}
    <p><td>{{ veterinarytreatment.treat_name }}</td></p>
    {% endfor %}

            <strong><P>Dane dotyczące wydania :</P></strong>
 {% for outcome in object.outcome_set.all %}
     <tr><td> Wydany w dniu: </td><td>{{ outcome.outcome_date }}r. </td></tr>
     <tr><td> Odbierający: </td><td>{{ outcome.o_name}}</td></tr>
     <tr><td> Adres: </td><td>{{ outcome.o_address }}</td></tr>
  {% endfor %}
     </body>
</html>
{% endblock %}

templates/animal_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Rejestracja nowego zwierzęcia: </h2>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Zarejestruj zwierzę"></form>
{% endblock %}

templates/animals_list.html
{% extends "base.html" %}

{% block title %}
{% endblock %}

{% block content %}

        <div class="border-top pt-3" style="text-align:right;">
            <a href="{% url 'new_animal' %}">Dodaj nowe zwierzę</a>
                <a href="{% url 'logout' %}">Wyloguj się</a>
        </div>

<div class="border-top pt-3" style="text-align:center;">
        <h3>Witamy w  Panelu administracyjnym</h3>

    </div>

    <div class="border-top pt-3" style="text-align:center;">
        <h3>Lista zwierząt ujętych w ewidencji schroniska:</h3>
    <p></p>
    </div>

    <div style="text-align:center;">
        <table style="text-align:center; width: 1700px; height: 300px;">
        <thead>
        <tr class="d-flex text-color-darker">
            <th scope="col" class="col-1 left">Lp.</th>
            <th scope="col" class="col-2 center">IMIĘ</th>
            <th scope="col" class="col-2 center">PRZYBLIŻONY WIEK</th>
            <th scope="col" class="col-2 center">RASA</th>
            <th scope="col" class="col-2 center">PŁEĆ</th>
            <th scope="col" class="col-2 center">UMASZCZENIE</th>
            <th scope="col" class="col-2 center">PRZEBYWA W SCHRONISKU</th>
            <th scope="col" class="col-2 center">CHIP</th>

        </tr>
        </thead>
            {% for animal in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href= "/animals/{{ animal.id }}"> {{ animal.name }}</a></td>
            <td>{{ animal.date_of_birth | timesince| cut:','}}</td>
            <td>{{ animal.breed }}</td>
            <td>{{ animal.gender }}</td>
            <td>{{ animal.color }}</td>
             {% if animal.is_active == True %}
                    <td> Tak </td>
                {% else %}
                    <td> Nie </td>
                {% endif %}
                {% if animal.chip_number == none %}
                    <td> Brak </td>
                {% else %}
                   <td>{{ animal.chip_number }}</td>
                {% endif %}
            {% endfor %}
        <tr>
        </table>

    </div>


            <div style="text-align:center;">
                <div class="col d-flex justify-content-center mb-2 noPadding">
                <form>
                    {% if page_obj.has_previous %}
                        <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4" value="{{ page_obj.previous_page_number }}" name="page">< poprzednia</button>
                    {% endif %}
                        <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4" value="{{ page_obj.number }}" name="page">{{ page_obj.number }}</button>
                    {% if page_obj.has_next %}
                        <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4" value="{{ page_obj.next_page_number }}" name="page">następna ></button>
                    {% endif %}
                </form>
                </div>
            </div>
{% endblock %}

templates/base.html
{%  load static %}

    <html lang="pl">
        <head>
            <meta charset="UTF-8">
                <title>Schronisko dla zwierząt</title>
        </head>
        <body>
            <main>
                {% block content %}
                {% endblock %}
            </main>
        </body>
    </html>

templates/health_care.html
{% block content %}
<h2>Karta zdrowia {{ animal.name }}</h2>
  <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
{% endblock %}

templates/login_form.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form action='' method="POST">
            {% csrf_token %}
                  <h3 class="color-header text-uppercase"> Zaloguj się </h3>
                {{ form }}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Zaloguj się</button>
            </div>
        </form>
    </div>

{% endblock content %}

templates/logout.html
{% extends "base.html" %}

{% block content %}
        <div>
            <h3 class="color-header text-uppercase"> Zostałeś wylogowany </h3>
        </div>
            <a href="{% url 'login' %}">Zaloguj się ponownie</a>
{% endblock %}

templates/main_page.html
{% extends 'base.html' %}

{% block content %}
    <header>
            <h3><a>Schronisko dla zwierząt</a></h3>
                <p>Zapraszamy</p>
            <nav>
                <ul>
                    <li><p><a href="{% url 'login' %}">Zaloguj się</a></p></li>
                        <li><p><a href="{% url 'register' %}">Zarejestruj się</a></p></li>
                </ul>
            </nav>
    </header>
{% endblock %}

templates/outcome_form.html
{% block content %}
<h2>Wydania {{ animal.name }}:</h2>
  <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
{% endblock %}

templates/register.html
{%  extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST">
        {% csrf_token %}
            <table>
                <tr><th><label for="id_username">Użytkownik:</label></th><td><input type="text" name="username" maxlength="150" required id="id_username"><br><span class="helptext">Wymagane jedynie litery, cyfry i @/./+/-/_.</span></td>
                <tr><th><label for="id_email">Adres email:</label></th><td><input type="email" name="email" maxlength="254" id="id_email"></td></tr>
                <tr><th><label for="id_first_name">Imię:</label></th><td><input type="text" name="first_name" maxlength="150" id="id_first_name"></td></tr>
                <tr><th><label for="id_last_name">Nazwisko:</label></th><td><input type="text" name="last_name" maxlength="150" id="id_last_name"></td></tr>
                <tr><th><label for="id_password">Password:</label></th><td><input type="password" name="password" required id="id_password"></td></tr>
                <tr><th><label for="id_confirm_password">Confirm password:</label></th><td><input type="password" name="confirm_password" required id="id_confirm_password"></td></tr>
            </table>
            <input type="submit" value="Utwórz konto">
        </form>
    </div>

{% endblock %}

templates/update_animal_form.html
{% extends 'base.html' %}

{% block content %}
 <h2>Edycja danych: </h2>
<form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form.as_p }}
    <div class="col d-flex justify-content-end mb-2 noPadding">
        <input class="btn btn-success" type="submit" value="Edytuj dane">
    </div>
</form>
{% endblock %}